//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiriClientConsole.BusStopServiceBinding {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://isrcorp.co.il/BusStop", ConfigurationName="BusStopServiceBinding.BusStopPortType")]
    public interface BusStopPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://isrcorp.co.il/BusStop/BusStopPortType/BusStopOperationRequest", ReplyAction="http://isrcorp.co.il/BusStop/BusStopPortType/BusStopOperationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SiriClientConsole.BusStopServiceBinding.BusStopOperationResponse BusStopOperation(SiriClientConsole.BusStopServiceBinding.BusStopOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://isrcorp.co.il/BusStop/BusStopPortType/BusStopResultOperationRequest", ReplyAction="http://isrcorp.co.il/BusStop/BusStopPortType/BusStopResultOperationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SiriClientConsole.BusStopServiceBinding.BusStopResultOperationResponse BusStopResultOperation(SiriClientConsole.BusStopServiceBinding.BusStopResultOperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isrcorp.co.il/BusStop")]
    public partial class BusStopRequestStructure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userField;
        
        private string requestIdField;
        
        private string lineNumberField;
        
        private string operatorField;
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="NMTOKEN", Order=0)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="NMTOKEN", Order=2)]
        public string lineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
                this.RaisePropertyChanged("lineNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=3)]
        public string @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("coordinate", typeof(LatLonCoordinate), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("radius", typeof(double), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("stopNumber", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=4)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isrcorp.co.il/BusStop")]
    public partial class LatLonCoordinate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double latField;
        
        private double lonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
                this.RaisePropertyChanged("lat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double lon {
            get {
                return this.lonField;
            }
            set {
                this.lonField = value;
                this.RaisePropertyChanged("lon");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isrcorp.co.il/BusStop")]
    public partial class StopDescription : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string stopNumberField;
        
        private string stopNameField;
        
        private string stopAddressField;
        
        private LatLonCoordinate stopCoordinateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string stopNumber {
            get {
                return this.stopNumberField;
            }
            set {
                this.stopNumberField = value;
                this.RaisePropertyChanged("stopNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string stopName {
            get {
                return this.stopNameField;
            }
            set {
                this.stopNameField = value;
                this.RaisePropertyChanged("stopName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string stopAddress {
            get {
                return this.stopAddressField;
            }
            set {
                this.stopAddressField = value;
                this.RaisePropertyChanged("stopAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public LatLonCoordinate stopCoordinate {
            get {
                return this.stopCoordinateField;
            }
            set {
                this.stopCoordinateField = value;
                this.RaisePropertyChanged("stopCoordinate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isrcorp.co.il/BusStop")]
    public partial class StopInfoStructure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StopDescription stopField;
        
        private string operatorField;
        
        private StopDescription destinationField;
        
        private StopStatusEnumeration stopStatusField;
        
        private System.DateTime[] etaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public StopDescription stop {
            get {
                return this.stopField;
            }
            set {
                this.stopField = value;
                this.RaisePropertyChanged("stop");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public StopDescription destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public StopStatusEnumeration stopStatus {
            get {
                return this.stopStatusField;
            }
            set {
                this.stopStatusField = value;
                this.RaisePropertyChanged("stopStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime[] eta {
            get {
                return this.etaField;
            }
            set {
                this.etaField = value;
                this.RaisePropertyChanged("eta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isrcorp.co.il/BusStop")]
    public enum StopStatusEnumeration {
        
        /// <remarks/>
        valid,
        
        /// <remarks/>
        endService,
        
        /// <remarks/>
        noData,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isrcorp.co.il/BusStop")]
    public partial class BusStopResultResponseStructure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseIdField;
        
        private string requestIdField;
        
        private string lineNumberField;
        
        private double radiusField;
        
        private bool radiusFieldSpecified;
        
        private ResponseStatusEnumeration statusField;
        
        private StopInfoStructure[] stopInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string responseId {
            get {
                return this.responseIdField;
            }
            set {
                this.responseIdField = value;
                this.RaisePropertyChanged("responseId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="NMTOKEN", Order=2)]
        public string lineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
                this.RaisePropertyChanged("lineNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
                this.RaisePropertyChanged("radius");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool radiusSpecified {
            get {
                return this.radiusFieldSpecified;
            }
            set {
                this.radiusFieldSpecified = value;
                this.RaisePropertyChanged("radiusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ResponseStatusEnumeration status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stopInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public StopInfoStructure[] stopInfo {
            get {
                return this.stopInfoField;
            }
            set {
                this.stopInfoField = value;
                this.RaisePropertyChanged("stopInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isrcorp.co.il/BusStop")]
    public enum ResponseStatusEnumeration {
        
        /// <remarks/>
        valid,
        
        /// <remarks/>
        invalidRequest,
        
        /// <remarks/>
        noneInRadius,
        
        /// <remarks/>
        noData,
        
        /// <remarks/>
        noStop,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isrcorp.co.il/BusStop")]
    public partial class BusStopResultRequestStructure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userField;
        
        private string responseIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="NMTOKEN", Order=0)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string responseId {
            get {
                return this.responseIdField;
            }
            set {
                this.responseIdField = value;
                this.RaisePropertyChanged("responseId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isrcorp.co.il/BusStop")]
    public partial class BusStopResponseStructure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIdField;
        
        private string responseIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string responseId {
            get {
                return this.responseIdField;
            }
            set {
                this.responseIdField = value;
                this.RaisePropertyChanged("responseId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BusStopOperation", WrapperNamespace="http://isrcorp.co.il/BusStop", IsWrapped=true)]
    public partial class BusStopOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public SiriClientConsole.BusStopServiceBinding.BusStopRequestStructure request;
        
        public BusStopOperationRequest() {
        }
        
        public BusStopOperationRequest(SiriClientConsole.BusStopServiceBinding.BusStopRequestStructure request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BusStopOperationResponse", WrapperNamespace="http://isrcorp.co.il/BusStop", IsWrapped=true)]
    public partial class BusStopOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public SiriClientConsole.BusStopServiceBinding.BusStopResponseStructure request;
        
        public BusStopOperationResponse() {
        }
        
        public BusStopOperationResponse(SiriClientConsole.BusStopServiceBinding.BusStopResponseStructure request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BusStopResultOperation", WrapperNamespace="http://isrcorp.co.il/BusStop", IsWrapped=true)]
    public partial class BusStopResultOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public SiriClientConsole.BusStopServiceBinding.BusStopResultRequestStructure request;
        
        public BusStopResultOperationRequest() {
        }
        
        public BusStopResultOperationRequest(SiriClientConsole.BusStopServiceBinding.BusStopResultRequestStructure request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BusStopResultOperationResponse", WrapperNamespace="http://isrcorp.co.il/BusStop", IsWrapped=true)]
    public partial class BusStopResultOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public SiriClientConsole.BusStopServiceBinding.BusStopResultResponseStructure request;
        
        public BusStopResultOperationResponse() {
        }
        
        public BusStopResultOperationResponse(SiriClientConsole.BusStopServiceBinding.BusStopResultResponseStructure request) {
            this.request = request;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BusStopPortTypeChannel : SiriClientConsole.BusStopServiceBinding.BusStopPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusStopPortTypeClient : System.ServiceModel.ClientBase<SiriClientConsole.BusStopServiceBinding.BusStopPortType>, SiriClientConsole.BusStopServiceBinding.BusStopPortType {
        
        public BusStopPortTypeClient() {
        }
        
        public BusStopPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusStopPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusStopPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusStopPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SiriClientConsole.BusStopServiceBinding.BusStopOperationResponse BusStopOperation(SiriClientConsole.BusStopServiceBinding.BusStopOperationRequest request) {
            return base.Channel.BusStopOperation(request);
        }
        
        public SiriClientConsole.BusStopServiceBinding.BusStopResultOperationResponse BusStopResultOperation(SiriClientConsole.BusStopServiceBinding.BusStopResultOperationRequest request) {
            return base.Channel.BusStopResultOperation(request);
        }
    }
}
